---
title: "NetCDF upload"
author: "Nick Jones"
date: "2024-09-04"
output: html_document
---

```{r setup, include=FALSE}
library(RNetCDF)
library(chron)
library(RColorBrewer)
library(lattice)
library(dplyr)
library(lubridate)
```

# Single File

```{r}

#open single file, if netcdf4 file use nc_open and ncvar_get
ncin <- open.nc("C:\\Users\\nj350\\OneDrive - Nova Southeastern University\\Documents\\Grants and Funding\\2024\\DEP CPR\\Jones_Fuess\\Data\\Satellite\\AQUA_MODIS.20140101.L3m.DAY.CHL.chlor_a.4km.NC", write=FALSE)

print.nc(ncin)

# search within the netcdf file to find the variables of interest

lat<-var.get.nc(ncin, "lat")
lon<-var.get.nc(ncin, "lon")
chl<- var.get.nc(ncin, "chlor_a")

#as this data is stored in wide format e.g., there's a matrix with lat on y and lon on x, with chl values in box, convert to long format
chlvec<- as.vector(chl)

#expand.grid plots every variable against each other therefore giving each data point, lat and lon (converts to long format)
lonlat<- as.matrix(expand.grid(lon, lat))

#create a matrix with longitude, latitude and environ variable
chl.day <- cbind(lonlat, chlvec)

#remove files to reduce data storage
rm(lonlat)
rm(chlvec)
rm(ncin)
chl.day <- na.omit(chl.day)
colnames(chl.day) <- c("Longitude", "Latitude", "Chlor_a")

head(chl.day)
summary(chl.day)

```

# Multiple files within a folder

```{r, results = 'hide'}

rm(list= ls())

folder <- "C:\\Users\\nj350\\OneDrive - Nova Southeastern University\\Documents\\Grants and Funding\\2024\\DEP CPR\\Jones_Fuess\\Data\\Satellite\\PAR AQUA"

files <- list.files(folder, full.names = T)

#creates a file 'nc' which contains all of the extracted data from the netcdf, if netcdf4 file use nc_open and ncvar_get
for(file in files) {
 nc <- open.nc(file)
  print.nc(nc)
}

#extracts specific variables from the data frame that are of interest and create a blank data frame 

coordinates <- c("lat", 
                 "lon")

variables <- "par"

times <- c("time_coverage_start",
           "time_coverage_end")

headers <- c(times, coordinates, variables)

df <- data.frame(matrix(ncol = length(headers), nrow = 0))
colnames(df) <- headers

#for each file in the folder perform the following steps
#1. find length of data
#2. create data frame
#3.add variables and global attributes to columns
#4.merge data frame with our blank data frame previously created

for(file in files) {
  nc <- open.nc(file)
  par_vec <- as.vector(var.get.nc(nc, "par"))
  num_df <- length(par_vec)
  
  newdf <- data.frame(matrix(ncol = length(headers), nrow = num_df))
  colnames(newdf) <- headers

  for (variable in variables) {
    
    newdf[variable] <- as.vector(var.get.nc(nc, "par"))
  }
  
  for(variable in coordinates) {
    
    newdf[variable] <- as.vector(var.get.nc(nc, variable))
  }

    for(global_attribute in times) {
    newdf[global_attribute] <- att.get.nc(nc, "NC_GLOBAL", global_attribute)
    }

  df <- merge(df, newdf, all=TRUE)
}  

#convert start and end dates to date format
df$time_coverage_start <- str_remove(df$time_coverage_start, "T.*")
df$time_coverage_end <- str_remove(df$time_coverage_end, "T.*")

#assigns date format to vector
df$Start.Date <- as.Date(df$time_coverage_start)
df$End.Date <- as.Date(df$time_coverage_end)

#removes dummy date vectors
df <- dplyr::select(df, -time_coverage_start, -time_coverage_end)

class(df$Start.Date)

df$Year <- str_remove(df$Start.Date, "-.*")
df$Month <- month(df$Start.Date)

#remove na values where no chlorophyll values as over land

df <- df %>%
  select(Start.Date, End.Date, Month, Year, lat, lon, par) %>%
  na.omit

```

# Write Data

```{r}

write.csv(df, "PAR conc.csv", row.names = F)

```

# Summarise Data

```{r}

annual.chl <- df %>%
    group_by(Year, lat, lon) %>%
  summarise(Max.chl = max(chlor_a), 
            Mean_chl = mean(chlor_a),
            sd_chl = sd(chlor_a))

```
